sudo mv hbase-client.jar.bak         hbase-client.jar         
sudo mv hbase-common.jar.bak         hbase-common.jar         
sudo mv hbase-examples.jar.bak       hbase-examples.jar       
sudo mv hbase-hadoop2-compat.jar.bak hbase-hadoop2-compat.jar 
sudo mv hbase-hadoop-compat.jar.bak  hbase-hadoop-compat.jar  
sudo mv hbase-it.jar.bak             hbase-it.jar             
sudo mv hbase-prefix-tree.jar.bak    hbase-prefix-tree.jar    
sudo mv hbase-protocol.jar.bak       hbase-protocol.jar       
sudo mv hbase-server.jar.bak         hbase-server.jar         
sudo mv hbase-shell.jar.bak          hbase-shell.jar          
sudo mv hbase-testing-util.jar.bak   hbase-testing-util.jar   
sudo mv hbase-thrift.jar.bak         hbase-thrift.jar         
