mv hbase-client.jar         hbase-client.jar.bak
mv hbase-common.jar         hbase-common.jar.bak
mv hbase-examples.jar       hbase-examples.jar.bak
mv hbase-hadoop2-compat.jar hbase-hadoop2-compat.jar.bak
mv hbase-hadoop-compat.jar  hbase-hadoop-compat.jar.bak
mv hbase-it.jar             hbase-it.jar.bak
mv hbase-prefix-tree.jar    hbase-prefix-tree.jar.bak
mv hbase-protocol.jar       hbase-protocol.jar.bak
mv hbase-server.jar         hbase-server.jar.bak
mv hbase-shell.jar          hbase-shell.jar.bak
mv hbase-testing-util.jar   hbase-testing-util.jar.bak
mv hbase-thrift.jar         hbase-thrift.jar.bak
