mv hbase-client.jar.bak         hbase-client.jar         
mv hbase-common.jar.bak         hbase-common.jar         
mv hbase-examples.jar.bak       hbase-examples.jar       
mv hbase-hadoop2-compat.jar.bak hbase-hadoop2-compat.jar 
mv hbase-hadoop-compat.jar.bak  hbase-hadoop-compat.jar  
mv hbase-it.jar.bak             hbase-it.jar             
mv hbase-prefix-tree.jar.bak    hbase-prefix-tree.jar    
mv hbase-protocol.jar.bak       hbase-protocol.jar       
mv hbase-server.jar.bak         hbase-server.jar         
mv hbase-shell.jar.bak          hbase-shell.jar          
mv hbase-testing-util.jar.bak   hbase-testing-util.jar   
mv hbase-thrift.jar.bak         hbase-thrift.jar         
